Build Icon Status Value kit
powerhome/playbook pull request #1022
Opened 2020-08-24 17:31 UTC by idanzonshein

#### Screens

[INSERT SCREENSHOT]

#### Breaking Changes

_Please reflect if your changes may break in some way (changes like removing/renaming props are examples of breaking changes)_

#### Runway Ticket URL

#### How to test this

#### Checklist:

- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review
- [ ] **SCREENSHOT** Please add a screen shot or two
- [ ] **SPECS** Please cover your changes with specs

2020-09-10 16:14 UTC, eabousaif approved these changes

2020-09-10 16:14 UTC, eabousaif commented on app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.scss
> +
Slight nitpick to clear out some of the empty lines here

2020-09-10 20:44 UTC, garettarrowood commented on app/pb_kits/playbook/_playbook.scss
> +@import 'pb_icon_stat_value/icon_stat_value';
This should be moved into alphabetical order above.

2020-09-10 20:44 UTC, garettarrowood commented on app/pb_kits/playbook/data/menu.yml
> +
Extra lines

2020-09-10 20:44 UTC, garettarrowood commented on app/pb_kits/playbook/packs/examples.js
> -
Leave this extra line

2020-09-10 20:45 UTC, garettarrowood commented on app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.html.erb
> +
Extra lines

2020-09-10 20:45 UTC, garettarrowood commented on app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.scss
> +
ditto

2020-09-10 20:46 UTC, garettarrowood requested changes
Great work on this! Only nit pick feedback from me.

2020-09-13 22:13 UTC, benlangfeld commented
Please merge master into this before adding the milano label back - the resource allocations on this branch are wrong and are alerting for quota exhaustion. /cc @iblackman

2020-09-14 13:59 UTC, garettarrowood commented
@benlangfeld -  I don't fully understand how deployment environments are used in playbook. Meaning, since we don't notify ninjas about testing these changes in playbook, who is using the deployment? Does it need to be there at all? Do we add the tag just to verify that things do deploy properly?  cc/ @thestephenmarshall

2020-09-14 14:03 UTC, idanzonshein commented
@benlangfeld Updated.

2020-09-14 14:03 UTC, garettarrowood approved these changes
LGTM

2020-09-14 16:23 UTC, thestephenmarshall requested changes
Nice work so far! Only a few nits (see the suggestions) and I think the spec for this kits needs a little more coverage.

2020-09-14 16:23 UTC, thestephenmarshall commented on app/pb_kits/playbook/_playbook.scss
> +@import './utilities/spacing';
```suggestion
@import './utilities/spacing';

```

We should not remove the extra line.

2020-09-14 16:23 UTC, thestephenmarshall commented on app/pb_kits/playbook/data/menu.yml
> +  - user_badge
```suggestion
  - user_badge
  
```

2020-09-14 16:23 UTC, thestephenmarshall commented on app/pb_kits/playbook/index.js
> +export IconStatValue from 'pb_icon_stat_value/_icon_stat_value.jsx'
```suggestion
export IconStatValue from 'pb_icon_stat_value/_icon_stat_value.jsx'
export IconValue from './pb_icon_value/_icon_value.jsx'
```

These are not alpha ordered.

2020-09-14 16:23 UTC, thestephenmarshall commented on app/pb_kits/playbook/packs/examples.js
> +import * as IconStatValue from 'pb_icon_stat_value/docs'
```suggestion
import * as IconStatValue from 'pb_icon_stat_value/docs'
import * as IconValue from 'pb_icon_value/docs'
```

Alpha ordering

2020-09-14 16:23 UTC, thestephenmarshall commented on app/pb_kits/playbook/packs/examples.js
> +  ...IconStatValue,
Alpha

2020-09-14 16:23 UTC, thestephenmarshall commented on spec/pb_kits/playbook/kits/icon_stat_value_spec.rb
> +      expect(subject.new(orientation: "vertical", size:"lg", variant: "royal").classname).to eq "pb_icon_stat_value_kit_vertical_lg_royal"
This is missing the other test cases which cover the other variants.

2020-09-15 13:05 UTC, jasperfurniss commented
Just removed the milano label because milano is at capacity. See the `Nitro Release Engineering` channel in Connect for more.

2020-09-15 13:44 UTC, garettarrowood commented
@jasperfurniss - I had a brief convo with @benlangfeld about Playbook milano this morning to gain some clarity for myself and the Champions. Here is what he had to say 

Ben: 
"... playbook doesn't use nearly as much in CPU/memory as nitro-web does. You can compare [the nitro-web quota](https://github.com/powerhome/APP/blob/master/application-namespaces/tier/beta/nitro-web-prs.yaml#L41-L60) to [the playbook quota](https://github.com/powerhome/APP/blob/master/application-namespaces/tier/beta/playbook-prs.yaml#L41-L60). Note that they are different pools. The [limit on number of nitro-web review stacks per cluster](https://github.com/powerhome/APP/blob/master/application-namespaces/tier/beta/nitro-web-prs.yaml#L6) is distinct from [that for playbook](https://github.com/powerhome/APP/blob/master/application-namespaces/tier/beta/playbook-prs.yaml#L6)."

So in other words - `nitro-web` and `playbook` deployments do not share the same resources. So removing the `milano` label here will not affect the limit reached that @rafbgarcia posted in the `Nitro Release Engineering` room in Connect.

2020-09-17 11:39 UTC, garettarrowood approved these changes

2020-09-28 14:00 UTC, coleerikson commented on app/pb_kits/playbook/index.js
> +export IconStatValue from 'pb_icon_stat_value/_icon_stat_value.jsx'
Is this missing a `./`?

2020-09-28 14:13 UTC, coleerikson commented on app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.rb
> +
Can any of these "unit, text, value" support validation types like "icon, size, variant, orientation"?

2020-09-28 14:13 UTC, coleerikson approved these changes
LGTM, had a couple comments.

2020-10-20 20:47 UTC, coleerikson commented on app/pb_kits/playbook/index.js
> +export IconStatValue from 'pb_icon_stat_value/_icon_stat_value.jsx'
Can confirm. This breaks in webpacker.

2020-10-20 20:49 UTC, coleerikson requested changes

2020-10-20 20:49 UTC, coleerikson commented on app/pb_kits/playbook/index.js
> +export IconStatValue from 'pb_icon_stat_value/_icon_stat_value.jsx'
Can confirm. This breaks in webpacker.

2020-11-17 16:29 UTC, coleerikson approved these changes

2020-11-17 16:36 UTC, thestephenmarshall commented
@garettarrowood sorry I missed your comment amongst others. So we do want to ensure the deployment completes. As of right now, if we want ninja testing on a PR here we do manually notify someone. We use the deployment env ourselves to ensure Playbook is operating as expected within the context of a given PR. This prevents us from having to constantly re-install locally and deal with the entropy for each given PR (which, for a UXer responsible for the release, could be upwards of 15 total). Hope that helps.

2020-11-17 16:39 UTC, thestephenmarshall approved these changes

2020-11-17 18:57 UTC, garettarrowood commented
@thestephenmarshall - It does. Thanks!

2020-11-19 19:24 UTC, merged

2020-11-19 20:22 UTC, garettarrowood commented
Woooohoooo!!!