Dark Mode Toggle
powerhome/playbook pull request #1051
Opened 2020-08-31 15:06 UTC by kre8sions

#### Screens

[INSERT SCREENSHOT]

#### Breaking Changes

_Please reflect if your changes may break in some way (changes like removing/renaming props are examples of breaking changes)_

#### Runway Ticket URL

#### How to test this

#### Checklist:

- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review
- [ ] **SCREENSHOT** Please add a screen shot or two
- [ ] **SPECS** Please cover your changes with specs

2020-09-01 15:29 UTC, thestephenmarshall commented
@kre8sions if this one is still WIP, you could convert to Draft.

2020-09-01 16:21 UTC, jasoncypret commented on app/helpers/playbook/pb_kit_helper.rb
> +      kit = build_view_model(kit.to_s, props.merge(dark: dark_mode), &block)
Can we do a test in playgrounds to make sure this doesn't break?

2020-09-01 16:22 UTC, jasoncypret commented on app/pb_kits/playbook/config/_kit_example.html.erb
> +      <div class="pb--doc <%= @dark == "true" ? 'dark_ui' : 'light_ui'%>">
Can we replace with a pb_card?

2020-09-01 16:23 UTC, jasoncypret commented on app/pb_kits/playbook/packs/site_styles/docs/_kit_doc.scss
> +      color: white;
Won't this hide potential problems in our dark kits? I think perhaps adding this only to the markdown sections might be better?

2020-09-01 16:23 UTC, jasoncypret commented on app/pb_kits/playbook/packs/site_styles/docs/_markdown.scss
> +    color: #fff;
```suggestion
    color: $white;
```

2020-09-08 19:05 UTC, jasoncypret requested changes

2020-09-08 19:05 UTC, jasoncypret commented on app/helpers/playbook/pb_doc_helper.rb
> +      # @dark = ENV["dark_mode"]
Remove?

2020-09-08 19:05 UTC, jasoncypret commented on app/pb_kits/playbook/_playbook.scss
> +@import 'pb_date_picker/date_picker';
I think you need to merge from 6.6.0  or master

2020-09-08 19:05 UTC, jasoncypret commented on app/pb_kits/playbook/packs/site_styles/docs/_kit_doc.scss
> +    }
```suggestion
    &.dark {
      color: $text_dk_light;
      a {
        color: $teal;
      }
    }
```

2020-09-08 19:05 UTC, jasoncypret commented on app/pb_kits/playbook/packs/site_styles/docs/_kit_doc.scss
> +  padding:$space_xl;
```suggestion
pre.highlight {
  padding: $space_xl;
```

2020-09-08 19:05 UTC, jasoncypret commented on app/pb_kits/playbook/packs/site_styles/docs/_markdown.scss
> +    h1,h2,h3,h4,h5,h6{
```suggestion
    h1,h2,h3,h4,h5,h6 {
```

2020-09-14 22:08 UTC, thestephenmarshall commented
@kre8sions somehow the branch is out of date. I think it might need `6.7.0` merged in!

2020-09-16 19:53 UTC, merged