[CMPN-22] Allow all HTML options on input in PbSelectableIcon, PbSelectableCard and PbSelectableCardIcon Rails kits
powerhome/playbook pull request #1113
Opened 2020-09-24 20:40 UTC by josephinef9

#### Runway Link

https://nitro.powerhrg.com/runway/backlog_items/CMPN-22 

#### Screens
Selectable card: 

<img width="408" alt="Screen Shot 2020-09-24 at 4 27 47 PM" src="https://user-images.githubusercontent.com/64423298/94197484-da9b4080-fe83-11ea-9aac-e7f465e5b353.png">
<img width="1064" alt="Screen Shot 2020-09-24 at 4 27 35 PM" src="https://user-images.githubusercontent.com/64423298/94197509-e555d580-fe83-11ea-8cf3-7c160139e7d0.png">

Selectable Icon: 

<img width="431" alt="Screen Shot 2020-09-24 at 4 26 22 PM" src="https://user-images.githubusercontent.com/64423298/94197620-06b6c180-fe84-11ea-8b36-45c06854ea78.png">
<img width="1024" alt="Screen Shot 2020-09-24 at 4 26 59 PM" src="https://user-images.githubusercontent.com/64423298/94197647-0fa79300-fe84-11ea-9453-755f33774208.png">

Selectable Card Icon: 

<img width="440" alt="Screen Shot 2020-09-24 at 4 26 00 PM" src="https://user-images.githubusercontent.com/64423298/94197747-35349c80-fe84-11ea-9b50-eb185753a921.png">
<img width="1057" alt="Screen Shot 2020-09-24 at 4 25 46 PM" src="https://user-images.githubusercontent.com/64423298/94197761-3b2a7d80-fe84-11ea-901f-f6ffddad3976.png">
 

#### Breaking Changes

[No (Explain)] - Only additive 

#### How to test this
Rspec tests have been written to cover changes. 

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `depreciation`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **URGENCY** Please select a release milestone
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

2020-09-29 11:18 UTC, garettarrowood commented on app/pb_kits/playbook/pb_selectable_card/_selectable_card.html.erb
> +<%= content_tag(:label,
Did you mean to leave this change? Can you change it back or provide some explanation?

2020-09-29 11:37 UTC, garettarrowood commented on app/pb_kits/playbook/pb_selectable_card/docs/example.yml
> +  - selectable_card_options: Options
Can we title all 3 of these doc additions "With Options" instead?

2020-09-29 11:39 UTC, garettarrowood commented on app/pb_kits/playbook/pb_selectable_card/selectable_card.rb
> +      prop :additional_input_options, type: Playbook::Props::Hash,
After talking with UX, to keep consistency across all kits with inputs, let's call this prop simply `input_options` instead. That means the two `input_options` methods you have in two of the kits here would be better renamed to `additional_input_options` (switch out the naming).

2020-09-29 11:40 UTC, garettarrowood requested changes
This looks great! See the comments above for some minor changes.

2020-09-29 14:01 UTC, garettarrowood approved these changes

2020-10-08 22:41 UTC, jasoncypret approved these changes

2020-10-09 12:28 UTC, jasperfurniss approved these changes

2020-10-14 13:04 UTC, merged