[NUXE-55] Updated styles to button toolbar kit
powerhome/playbook pull request #1129
Opened 2020-10-01 17:35 UTC by christinaatai

#### Screens

<img width="994" alt="Screen Shot 2020-10-01 at 1 34 21 PM" src="https://user-images.githubusercontent.com/42459486/94843564-dbcfee80-03ea-11eb-9f59-4a89e236a276.png">
<img width="994" alt="Screen Shot 2020-10-01 at 1 34 28 PM" src="https://user-images.githubusercontent.com/42459486/94843571-dffc0c00-03ea-11eb-90d4-e33b6092cdc9.png">
<img width="997" alt="Screen Shot 2020-10-01 at 1 34 02 PM" src="https://user-images.githubusercontent.com/42459486/94843581-e2f6fc80-03ea-11eb-9a00-29e647298cbe.png">
<img width="990" alt="Screen Shot 2020-10-01 at 1 34 09 PM" src="https://user-images.githubusercontent.com/42459486/94843588-e5f1ed00-03ea-11eb-9410-f7dc89919237.png">

#### Breaking Changes

No, this kit is not being used in Nitro yet.

#### Runway Ticket URL

https://nitro.powerhrg.com/runway/backlog_items/NUXE-55

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `depreciation`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **URGENCY** Please select a release milestone
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

2020-10-07 15:55 UTC, jasoncypret requested changes
I'd like to improve some of the CSS & SASS.

Looking at other design systems, I think we need to not allow these buttons to float to two lines. `white-space: nowrap;`

The readability and length of this file concern me. I'd recommend possibly breaking up the file into horizontal and vertical variants, removing duplicated CSS (like the button hovers for example).

I'd like to go through the whole file and look for all the duplications. See if they can be eliminated in a smart way

2020-10-07 15:55 UTC, jasoncypret commented on app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.scss
> +}
These could possibly be combined into 1 mixin

2020-10-07 15:55 UTC, jasoncypret commented on app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.scss
> +          }
This seems to be the same as lines 145-155 can you eliminate one by moving it to the parent class?

2020-10-07 15:55 UTC, jasoncypret commented on app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.scss
> +          }
Same...seems like we can eliminate

2020-10-07 15:55 UTC, jasoncypret commented on app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.scss
> +}
Another thought is moved to a separate mixin file to make this a bit more readable

2020-10-07 15:55 UTC, jasoncypret commented on app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.scss
> +      &[class*=_primary].dark {
Consider making a separate file or mixin

2020-10-07 15:55 UTC, jasoncypret commented on app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_default.jsx
> +      />
Can we think of other examples for the button text? These are very power specific, and also I think we can get creative here. See the nav examples for inspiration

2020-10-08 21:20 UTC, jasperfurniss approved these changes

2020-10-08 22:13 UTC, jasoncypret approved these changes

2020-10-08 23:56 UTC, merged