[NUXE-212] KIT DEV- Input Group Kit
powerhome/playbook pull request #1189
Opened 2020-11-03 17:56 UTC by adub65

#### Screens

[INSERT SCREENSHOT]

#### Breaking Changes

[Yes/No (Explain)]

#### Runway Ticket URL
https://nitro.powerhrg.com/runway/backlog_items/NUXE-212

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **URGENCY** Please select a release milestone
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

2020-11-09 21:39 UTC, thestephenmarshall commented
@adub65 - looks like this one needs to have `v7.7.0` merged into it. This will likely result in some conflicts, so be sure to reach out if you need extra eyes on it.

2020-11-09 21:39 UTC, thestephenmarshall commented on CHANGELOG.md
> +
This change shouldn't be here.

2020-11-09 21:53 UTC, thestephenmarshall commented on Gemfile.lock
> +    playbook_ui (7.4.1)
`7.6.2` is the latest branch

2020-11-11 14:37 UTC, bh247484 reviewed
This looks good barring alpha testing results.  Removed all unrelated file changes.

2020-11-11 16:11 UTC, thestephenmarshall commented
@adub65 on the Form Group React Typeahead example, I am seeing this:

<img width="245" alt="Screen Shot 2020-11-11 at 10 08 56 AM" src="https://user-images.githubusercontent.com/2293844/98835405-ffcd1980-2405-11eb-8783-8a45cd30a8fa.png">

On the Rails version, it looks like your width is working but I get no results:

<img width="379" alt="Screen Shot 2020-11-11 at 10 10 34 AM" src="https://user-images.githubusercontent.com/2293844/98835588-3b67e380-2406-11eb-85ce-54c6d9b83d16.png">

2020-11-11 16:12 UTC, thestephenmarshall requested changes
I think there is a little more tweaking for the React Typeahead example. Looks like the width isn't working there. This is likely bc the React version uses the [react-select](https://react-select.com) lib.

2020-11-11 16:26 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
> +
```suggestion
& > [class^=pb_typeahead_kit] {
  min-width: 200px;
}
```

I would suggest adding this to fix the issue with the React version of Typeahead example being too narrow. 

<img width="1904" alt="Screen Shot 2020-11-11 at 10 26 16 AM" src="https://user-images.githubusercontent.com/2293844/98837263-618e8300-2408-11eb-9c67-363a41537a05.png">

2020-11-12 17:50 UTC, thestephenmarshall approved these changes

2020-11-12 18:18 UTC, thestephenmarshall requested changes
On the Rails version of the Typeahead group, you will want to add the inline script tag which handles the selection of options or else the doc for that example will not allow you to choose anything. Let me know if you have any questions.

2020-11-16 22:47 UTC, thestephenmarshall approved these changes
@adub65 Nice work! Let's make Typeahead examples into a new ticket to work separately given there are concerns around color and multi-line. cc @jasoncypret

2020-11-19 19:23 UTC, merged