Updated design for date time stacked
powerhome/playbook pull request #1268
Opened 2020-12-16 17:00 UTC by evalouderback

This PR includes updates to Date Stacked (to add the bold variant), Date Time Stacked, and Section Separator (to get rid of that spacing on the react version for Date Time Stacked). 

I think maybe the Section Separator kit needs to be updated, because as you can see on Date Time Stacked, if you have the year displaying, the time is not center aligned. If you switch the Flex kit wrapping it to use `align-items: center` instead of `align-items: stretch`, the Section Separator for some reason disappears. This behavior also happens if you switch it to `align-items: center` on the kit itself.

#### Screens

**Date Stacked:**
<img width="1433" alt="Screen Shot 2020-12-16 at 11 56 06 AM" src="https://user-images.githubusercontent.com/50629488/102380364-d3bd2f00-3f95-11eb-901c-343f844bbc50.png">
<img width="1433" alt="Screen Shot 2020-12-16 at 11 56 19 AM" src="https://user-images.githubusercontent.com/50629488/102380389-dc156a00-3f95-11eb-8ad2-902d6633cb44.png">

**Date Time Stacked:**
<img width="1431" alt="Screen Shot 2020-12-16 at 11 55 29 AM" src="https://user-images.githubusercontent.com/50629488/102380419-e5063b80-3f95-11eb-887d-52d8e4bc4fdd.png">

**Section Separator (no visual changes):**
<img width="1432" alt="Screen Shot 2020-12-16 at 11 56 48 AM" src="https://user-images.githubusercontent.com/50629488/102380444-eafc1c80-3f95-11eb-8dab-df3325506fe2.png">

#### Breaking Changes

No
#### Runway Ticket URL

[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/NUXE-58)
#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **URGENCY** Please select a release milestone
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

2020-12-16 20:21 UTC, jasoncypret requested changes
A couple of nits

2020-12-16 20:21 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.scss
> +    padding-bottom: 10px !important;
```suggestion
    padding-bottom: ($space_xs + 2) !important;
```

Let's try and use variables even if they are slightly custom

2020-12-16 20:21 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.scss
> +  padding-right: 3px;
```suggestion
  padding-right: ($space_xs / 2);
```

2020-12-16 20:21 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/_date_time_stacked_dark.jsx
> +        date={new Date('20 Mar 2018')}
@coleerikson Is this date correct?

2020-12-16 20:25 UTC, jasoncypret commented
I'm not sure the dates are correct. For example, the top example is 1 hour off. The second uses eastern but is at 1a. React example:

![image](https://user-images.githubusercontent.com/863031/102402349-433d1980-3faa-11eb-89e7-dfbf750e1145.png)

2020-12-16 20:25 UTC, jasoncypret requested changes
Remove the dark example. No longer needed after dark mode

![image](https://user-images.githubusercontent.com/863031/102402555-92834a00-3faa-11eb-8194-85d9efab279d.png)

2020-12-16 20:27 UTC, jasoncypret requested changes
![image](https://user-images.githubusercontent.com/863031/102402656-bc3c7100-3faa-11eb-9e41-274636cfc88b.png)

Time is not setup correctly

2020-12-16 20:28 UTC, jasoncypret requested changes
![image](https://user-images.githubusercontent.com/863031/102402748-d9713f80-3faa-11eb-9204-d81dce35e3dc.png)

React dark mode not working. Follow how the docs are setup for other react kits. See the `{...props}` things...

2021-01-04 19:26 UTC, thestephenmarshall commented
This one appears to still need some work. Any updates in flight @evalouderback?

2021-02-02 21:26 UTC, thestephenmarshall commented
Passing this one back to you @evalouderback

2021-03-04 21:59 UTC, closed without merging