Update to Time Stacked
powerhome/playbook pull request #1290
Opened 2021-01-05 16:16 UTC by evalouderback

Rails complete.

#### Screens

[INSERT SCREENSHOT]

#### Breaking Changes

[Yes/No (Explain)]

#### Runway Ticket URL

[INSERT URL]

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **URGENCY** Please select a release milestone
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

2021-02-02 21:39 UTC, coleerikson commented on playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.html.erb
> +      <time>
I think the time itself can be added as an attribute on the time element if you wanted to do that, but I think I remember just doing the wrap like below is cool too. `<time datetime="${object.pb_date_time.etc}">` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time.

2021-02-02 21:40 UTC, coleerikson commented on playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.jsx
> +  if (props.date) deprecatedProps('Time Stacked', ['date']) //date prop is deprecated, use time instead
<3

2021-02-02 21:42 UTC, coleerikson commented on playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.jsx
> +        <time>
Same comment here regarding attributes.

2021-02-02 21:46 UTC, coleerikson approved these changes
Looks good, left some clarifying comments.

2021-02-11 22:59 UTC, jasoncypret approved these changes

2021-02-11 23:24 UTC, jasoncypret requested changes
@coleerikson @evalouderback can you add the places in Nitro this kit is used (if any). Those will need to be updated in my Nitro PR

2021-02-24 19:07 UTC, kre8sions commented
@evalouderback @coleerikson I am leaving this Pr out of 8.1.0s release there is still more work based on @jasoncypret 's comment

2021-02-24 21:57 UTC, jasoncypret approved these changes

2021-02-25 17:45 UTC, merged