Accessibility Improvements, Color Fixes, Menu Changes
powerhome/playbook pull request #1405
Opened 2021-03-24 19:38 UTC by kre8sions

#### Screens

[INSERT SCREENSHOT]

#### Breaking Changes

[Yes/No (Explain)]

#### Runway Ticket URL

[INSERT URL]

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **URGENCY** Please select a release milestone
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

*The normal release cut off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

2021-03-26 18:33 UTC, coleerikson commented on playbook/app/pb_kits/playbook/pb_textarea/_textarea.scss
> +      textarea {
Suggestion: put this in the same level as `&.error`?

2021-03-26 18:34 UTC, coleerikson commented on playbook/app/pb_kits/playbook/pb_textarea/_textarea.scss
> +      border-color: rgba($white,.15);
Suggestion: Space after comma, and add 0. ie `rgba($white, 0.15)`;

2021-03-26 18:35 UTC, coleerikson commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +        background-color: rgba($border_light,.50);
Suggestion: Space after comma, and add 0. ie `rgba($white, 0.15)`;

2021-03-26 18:35 UTC, coleerikson commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +        background-color: rgba($white,.1);
Suggestion: Space after comma, and add 0. ie `rgba($white, 0.15)`;

2021-03-26 18:36 UTC, coleerikson commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
>        > trix-editor {
Suggestion: put this in the same level as &.error?

2021-03-26 19:26 UTC, coleerikson approved these changes
Minor recommendations to my tastes but nothing major. Spacing primarily within `rgba` as well as adding a 0 to the decimals. Also reducing SCSS nesting if the "parent" only has 1 child.

2021-03-26 20:52 UTC, jasoncypret commented
Looking pretty solid. I need to test light mode a bit more on Monday. FYI @kre8sions

2021-03-29 19:32 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
>        transition: background-color 5000s ease-in-out 0s;
Please add a transition to this border color (As well as all of them)

2021-03-29 19:34 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +    }
Add a transition. This is too abrupt

2021-03-29 19:37 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
>      // Dark Mode Placeholder
For some reason, the dark mode background transition is slower on the bar than it is in the text area. Let's sync those or perhaps remove the transition on the bar.

2021-03-29 19:40 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_select/_select.scss
> +    }
Transition

2021-03-31 12:45 UTC, jasperfurniss approved these changes

2021-03-31 12:45 UTC, jasperfurniss commented on playbook/app/pb_kits/playbook/data/menu.yml
> +    - rich_text_editor
makes sense. 👍

2021-03-31 12:45 UTC, jasperfurniss commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +
Can we get rid of the extra space here?

2021-03-31 12:45 UTC, jasperfurniss commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +  //Disables the predefined transition values
Can we just get rid of this code too?

2021-03-31 12:45 UTC, jasperfurniss commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +  //  transition: none !important;
Can we just get rid of this code too?

2021-03-31 12:45 UTC, jasperfurniss commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +
Can we get rid of this extra space?

2021-03-31 12:51 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +        border-color:$active_dark;
Space after selector

2021-03-31 12:51 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +      trix-editor {
Space

2021-03-31 12:51 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +      trix-editor {
Space

2021-03-31 12:51 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
> +      color: $white;
Space

2021-03-31 12:53 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_select/_select.scss
> +
Any reason for this return?

2021-03-31 12:54 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
> +      .text_input:hover{
Space

2021-03-31 12:54 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
> +    .typeahead-kit-select__indicator:hover{
Space

2021-03-31 12:55 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
> +    .pb_list_kit{
Space

2021-03-31 12:55 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
> +    .text_input_value_container{
Space

2021-03-31 12:56 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_textarea/_textarea_mixin.scss
> +@mixin transition_default{
Space

2021-03-31 15:39 UTC, jasoncypret requested changes
![image](https://user-images.githubusercontent.com/863031/113171696-58fae580-920d-11eb-9702-497c4bd23da2.png)
Rich text need some help

2021-03-31 15:42 UTC, jasoncypret commented
This also appears off 
![image](https://user-images.githubusercontent.com/863031/113172171-cad32f00-920d-11eb-8c64-373357b473a4.png)

2021-04-01 16:39 UTC, jasoncypret approved these changes

2021-04-01 19:14 UTC, merged