added border radius to visual guidelines pb
powerhome/playbook pull request #1648
Opened 2021-11-16 20:35 UTC by RexGluck

#### Screens

[INSERT SCREENSHOT]
![Screen Shot 2021-11-16 at 3 33 54 PM](https://user-images.githubusercontent.com/89551222/142061396-d24dc110-3bdc-461f-bd2a-29543bee62da.png)

#### Breaking Changes

[Yes/No (Explain)]

#### Runway Ticket URL

[https://nitro.powerhrg.com/runway/backlog_items/PLAY-8]

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

2021-11-17 13:58 UTC, kre8sions requested changes
![Image 2021-11-17 at 8 39 51 AM](https://user-images.githubusercontent.com/9784112/142214232-405ddae3-c753-4dd6-b7ff-ba7ecff0947f.jpg)

2021-11-17 13:58 UTC, kre8sions commented on playbook-website/app/javascript/site_styles/_visual_guidelines.scss
> +  margin: 0px 10px 0px 0px !important;
Let's use our spacing variables or we can use the margin classes on the actual div themselves and delete it from here.

2021-11-17 13:58 UTC, kre8sions commented on playbook-website/app/javascript/site_styles/_visual_guidelines.scss
> +  height: 100px !important;
Let's remove all !important tags

2021-11-17 13:58 UTC, kre8sions commented on playbook-website/app/javascript/site_styles/_visual_guidelines.scss
> +  height: 100px !important;
@RexGluck

2021-11-17 18:52 UTC, jasoncypret commented
It's looking great. Let's just get some microscopy added!!

![Border Radius](https://user-images.githubusercontent.com/863031/142263961-05405f27-52f5-430d-b8ff-47b96026b57a.png)

2021-11-17 18:54 UTC, jasoncypret commented
@RexGluck you've got conflicts.

```
git checkout master
git pull
git checkout [yourbranch]
git merge origin/master
git push --force-with-lease
```

If you get conflicts just accept all incoming.

2021-11-18 16:50 UTC, jasoncypret commented
LGTM 🚀

2021-11-18 16:56 UTC, jasoncypret requested changes
Just a couple of tweaks. Remind me to show you some fancy sass selector magic. 😉

2021-11-18 16:56 UTC, jasoncypret commented on playbook-website/app/javascript/site_styles/_visual_guidelines.scss
> +  }
In order to keep this file clean lest move this into a partial and import it here.

Also you need a space after your selector and your curly brace `.selector {`

2021-11-18 16:56 UTC, jasoncypret commented on playbook-website/app/views/pages/visual_guidelines_partials/_border_radius.html.erb
> +    <% react_contents = Rails.root.join("app/views/pages/code_snippets/border_radius_tokens.txt").read %>
```suggestion
    <% border_radius_tokens = Rails.root.join("app/views/pages/code_snippets/border_radius_tokens.txt").read %>
```

We will probably have another story to move these to the controller. In the meantime, let's rename some this does not collide with anyone else.

2021-11-18 22:59 UTC, jasoncypret approved these changes

2021-11-18 23:00 UTC, merged