Add Global Shadow Props to ALL kits
powerhome/playbook pull request #1686
Opened 2021-12-02 16:00 UTC by pauljpark

#### Screens
***Screenshots here are just for PROOF OF CONCEPT***

<img width="805" alt="Screen Shot 2021-12-02 at 9 50 03 AM" src="https://user-images.githubusercontent.com/60274468/144454925-0f182fc6-86db-43f7-8e11-0b9add463dd1.png">

<img width="805" alt="Screen Shot 2021-12-02 at 9 50 38 AM" src="https://user-images.githubusercontent.com/60274468/144454950-12a0cbb7-5b17-4405-80c0-3a359972d443.png">

#### Breaking Changes

[Yes/No (Explain)]

#### Runway Ticket URL

https://nitro.powerhrg.com/runway/backlog_items/PLAY-31

#### How to test this

***FOR REACT***
Pass one of the values `none | deep | deeper | deepest` to `shadow` on a kit `eg. _button_default.jsx` which will look like `eg. shadow="deepest"` within that component. Some kits will override the prop so the shadow style will not be applied to such kits.

***FOR RAILS***
Pass one of the values `none | deep | deeper | deepest` to `shadow` on a kit `eg. _button_default.html.erb` which will look like `eg. shadow: "deepest"` within that component. Some kits will override the prop so the shadow style will not be applied to such kits.

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

2021-12-03 20:27 UTC, thestephenmarshall approved these changes
Thank you for the attention to detail on this one. Looks great to me! :shipit:

2021-12-06 14:51 UTC, jasoncypret requested changes

2021-12-06 14:51 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/utilities/_shadow.scss
> +$shadow_deepest: 0 30px 38px 4px $shadow, 0 2px 14px 4px rgba($shadow, 0.1);
```suggestion
@import "../tokens/exports/shadows";
```

No need to redefine this here. It already exists as a token

2021-12-06 14:51 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/utilities/_shadow.scss
> +}
```suggestion
@mixin shadow-classes($shadows-list) {
  @each $name, $shadow in $shadows-list {
    .shadow_#{$name} {
      box-shadow: $shadow;
    }
  }
}

@include shadow-classes($box_shadows);
```

Let's make this smarter. We already have an awesome map we can loop over to dynamically generate these.

2021-12-06 15:54 UTC, jasoncypret requested changes
One more: 

![image](https://user-images.githubusercontent.com/863031/144878145-da590c8a-181d-40f1-a1b3-905bacf88c4b.png)

The shadows are no longer showing on the docs view. Can you investigate and fix?

2021-12-06 20:02 UTC, jasoncypret approved these changes

2021-12-06 20:03 UTC, merged