[Play-62] Updating size for icon on variant prop
powerhome/playbook pull request #1731
Opened 2022-01-19 16:35 UTC by jon1735

#### Screens

BEFORE PIC DESKTOP VIEW: 
<img width="229" alt="variantpic" src="https://user-images.githubusercontent.com/84339183/150173700-e88c0ae7-67ae-4a94-9410-3b03061d60ba.png">

AFTER PIC DESKTOP VIEW: 
<img width="324" alt="Screen Shot 2022-01-19 at 11 33 05 AM" src="https://user-images.githubusercontent.com/84339183/150174055-ab5c8f65-7725-49e8-b735-581bd4f09c56.png">

#### Breaking Changes

No breaking change 

#### Runway Ticket URL

https://nitro.powerhrg.com/runway/backlog_items/PLAY-62

#### How to test this

Go to the date kit, scroll down to the variants option.... notice the icon size change. (reference pictures)

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

2022-01-27 20:25 UTC, thestephenmarshall reviewed
@jon1735 looks like this PR just needs [this one](https://github.com/powerhome/playbook/pull/1731/commits/6f628eef73e2bfda62b1cb11e0ad14b24c8edd16) commit. Can you confirm?

2022-01-31 14:57 UTC, jon1735 commented
> this one

Good morning stephen, i'm currently working on resolving these merge conflicts. Should be ready momentarily.

2022-01-31 14:57 UTC, jon1735 commented
@thestephenmarshall Currently working on resolving merge conflicts, will be done momentarily

2022-01-31 15:27 UTC, thestephenmarshall requested changes
@jon1735 I cannot tell what is going on in this PR partly because your commits are named `Merge master` (and similar). Commit history is of absolute importance to you and to reviewers. While the prior issue with upstream commit history is to blame (that's me), looking at this PR is difficult when I cannot tell which commits are yours.

2022-01-31 15:31 UTC, jon1735 commented
Also for reference, the Commit is titled: Updating size for icon on variant prop.... commit :6f628eef73e2bfda62b1cb11e0ad14b24c8edd16 @thestephenmarshall

2022-01-31 20:59 UTC, thestephenmarshall approved these changes

2022-01-31 20:59 UTC, merged