WIP Add flexbox props to all kits
powerhome/playbook pull request #1750
Opened 2022-01-27 17:20 UTC by RobGentile17

#### Screens

[INSERT SCREENSHOT]

#### Breaking Changes

[Yes/No (Explain)]

#### Runway Ticket URL

[INSERT URL]

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

2022-02-14 17:55 UTC, jasperfurniss approved these changes

2022-02-14 18:00 UTC, jasoncypret requested changes

2022-02-14 18:05 UTC, RobGentile17 commented on playbook/app/pb_kits/playbook/_playbook.scss
> +@import './utilities/order';
I just updated it, is that what you meant? @jasoncypret

2022-02-14 18:06 UTC, RobGentile17 commented on playbook/app/pb_kits/playbook/_playbook.scss
> +@import './utilities/flexbox';
@jasoncypret here is the new import

2022-02-14 18:07 UTC, RobGentile17 commented on playbook/app/pb_kits/playbook/utilities/_flexbox.scss
> +@import './flex_direction';
@jasoncypret here's the new scss file

2022-02-15 19:27 UTC, thestephenmarshall approved these changes

2022-02-15 19:28 UTC, thestephenmarshall commented
@RobGentile17 not sure about the conflict, but looks like it's time to GTM. 🚀

2022-02-15 19:30 UTC, jasoncypret approved these changes

2022-02-16 13:17 UTC, kre8sions reviewed
- We need to add !important to the scss flex styles.
- Also I noticed you are using flexStart and flexEnd if you are going to have those also add the normal start and end to the props where that is used @RobGentile17

2022-02-16 15:11 UTC, merged