Lightbox Component
powerhome/playbook pull request #1772
Opened 2022-02-09 19:42 UTC by jasperfurniss

2022-02-11 20:58 UTC, thestephenmarshall requested changes
This one is going to be a little tricky. Need to determine the circular dependency situation out.

2022-05-11 15:14 UTC, Ivancandido11 commented on playbook/app/pb_kits/playbook/pb_lightbox/_lightbox_header.jsx
> +                  text="All Photos"
Im assuming at some point this will be used for something, instead of just text. I can remove it though if we don't want it here for now.

2022-06-07 19:23 UTC, thestephenmarshall reviewed
This seems to be missing some pretty basic interactivity:

- ESC to close
- Left/Right Arrow navigation

I think these should be added at the very least before this PR will be ready.

2022-06-07 22:47 UTC, thestephenmarshall approved these changes
Approving so the hold is released. Still more work to do.

2022-06-07 22:47 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Slides.jsx
> +  // onClick = noop,
Remove

2022-07-22 17:15 UTC, thestephenmarshall commented
@jasperfurniss have a look, but this one is good to go imo!

2022-07-26 14:51 UTC, merged