Addressing deprecation warning in order to avoid using Kernel.open
powerhome/playbook pull request #1778
Opened 2022-02-14 18:17 UTC by delucas

#### Breaking Changes

No. Should address a single Deprecation Warning.

#### Runway Ticket URL

[HFH-705](https://nitro.powerhrg.com/runway/backlog_items/HFH-705)

#### How to test this

[INSERT TESTING DETAILS]

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

2022-02-14 18:21 UTC, thestephenmarshall commented
@delucas thanks for opening this PR. I am deploying to milano and will check the results soon.

2022-02-14 20:04 UTC, thestephenmarshall requested changes
@delucas Looks like something is blowing up in this PR https://pr1778.playbook.beta.hq.powerapp.cloud/kits/icon/rails

2022-02-16 16:12 UTC, thestephenmarshall approved these changes

2022-02-16 18:19 UTC, delucas commented
@thestephenmarshall thanks!
How is the workflow in Playbook? Should I merge? When is the new version of the gem released?
Is that something you do in batches?
Sorry about that, just don't know how to proceed.

2022-03-16 03:10 UTC, merged