Dialog Kit shows a strange border intermittently
powerhome/playbook pull request #1810
Opened 2022-03-07 19:19 UTC by kellyeryan

#### Problem 

Sometimes for some people the dialog kit has a border on the right and bottom sides. I have changed the scss from `overflow: scroll` to `overflow:auto` and this fixed the problem for me.

#### Screens

PROBLEM:
<img width="1582" alt="Screen Shot 2022-03-07 at 1 58 42 PM" src="https://user-images.githubusercontent.com/51907753/157102322-5048d3d8-96dd-41c7-9383-91c32b4da6ef.png">

SOLUTION:
<img width="1578" alt="Screen Shot 2022-03-07 at 2 00 37 PM" src="https://user-images.githubusercontent.com/51907753/157102375-fc1e0a20-1453-443a-a284-0b725577773e.png">

#### Breaking Changes

No. This change shouldn't break anything.

#### How to test this

Check to make sure the dialog kit is working without the strange border. For some people this bug was not reproducible and we're not sure why.

#### Checklist:

- [X] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [X] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [X] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [X] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

2022-03-07 21:14 UTC, thestephenmarshall commented
@kellyeryan couple of questions:

1. Are you using an external mouse or the built-in track pad?
2. Does this happen for other people you have interacted with? 

For me, I cannot reproduce this on either machine I've tried thus far.

2022-03-07 21:54 UTC, thestephenmarshall commented
I think we might not be able to reliably fix this issue for everyone since the culprit is outside of the source code.

2022-03-07 21:56 UTC, kellyeryan commented
Rodolfo says that it works for the resolution as well so we've helped with that and the mouse at least.

2022-03-10 13:35 UTC, rodolfoasantos commented
Hey @thestephenmarshall!  I can consistently reproduce this bug. I could easily reproduce it using an external monitor. But since you mention an `external mouse` issue, I gave a try as well and seems fixed.

here are some examples:

1 - Using an external monitor.
![CleanShot 2022-03-10 at 10 20 00](https://user-images.githubusercontent.com/754389/157670835-631575e3-6e4c-4826-9521-e6e17af196a9.png)


![CleanShot 2022-03-10 at 10 18 34](https://user-images.githubusercontent.com/754389/157670968-c8777686-a426-4391-881a-8cd45c8034c9.gif)




2 - Using my macbook and a external mouse
![CleanShot 2022-03-10 at 10 30 12@2x](https://user-images.githubusercontent.com/754389/157672187-270d2661-0be7-4a75-8555-2df084836461.png)




3 - Only using my macbook without external mouse (macbook's trackpad)

![CleanShot 2022-03-10 at 10 29 01@2x](https://user-images.githubusercontent.com/754389/157672322-baa877a9-0ebf-4988-85f3-ff811803bc11.png)

2022-03-16 14:50 UTC, kellyeryan commented
@thestephenmarshall Should I close this? If you get a chance, please block or approve.

2022-03-16 14:52 UTC, thestephenmarshall commented
This is not on the radar and considered low priority.

2022-03-16 14:57 UTC, thestephenmarshall requested changes
This needs alpha testing.

2022-03-28 15:54 UTC, thestephenmarshall approved these changes
Marking this one as ready @kellyeryan. We will have to keep a collective set of eyes out for any anomalies once merged.

2022-03-28 16:26 UTC, merged