[PLAY-248] Alert Dialog Cleanup
powerhome/playbook pull request #2030
Opened 2022-08-26 14:50 UTC by Israel-Molestina

#### Screens

![Screen Shot 2022-08-26 at 10 47 09 AM](https://user-images.githubusercontent.com/73671109/186931578-f786cb93-f103-4c2f-b8a7-4be472c76f32.png)
![Screen Shot 2022-08-26 at 10 47 15 AM](https://user-images.githubusercontent.com/73671109/186931642-c8b1e20f-fd0b-44f7-805d-3c100b4322c7.png)
![Screen Shot 2022-08-26 at 10 47 21 AM](https://user-images.githubusercontent.com/73671109/186931653-aeca4fe0-b78b-48a4-a68c-1300c37a004f.png)
![Screen Shot 2022-08-26 at 10 47 26 AM](https://user-images.githubusercontent.com/73671109/186931668-d3eb4530-4a4e-4179-83f4-fcaea3850b74.png)
![Screen Shot 2022-08-26 at 10 47 31 AM](https://user-images.githubusercontent.com/73671109/186931684-14272565-0a37-4420-827d-440871bb96a9.png)

#### Breaking Changes

NO

#### Runway Ticket URL

[RUNWAY URL](https://nitro.powerhrg.com/runway/backlog_items/PLAY-248)

#### How to test this

Pull this branch and run yarn test-watch for jest test and cd playbook && ./test.sh for rails test. 

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

2022-08-26 14:57 UTC, nidaqg approved these changes
Looks good!

2022-08-29 16:55 UTC, jasperfurniss commented
Needs jest tests.

2022-08-29 16:56 UTC, jasperfurniss commented
Once this has been finally reviewed tomorrow with @RexGluck, I'll take a look again at your PR and get it merged into the next release cycle.

2022-08-30 20:37 UTC, jasperfurniss commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
> +  // const [singleButtonOpen, toggleSingleButtonOpen] = useDialog()
Let's remove all these comments.

2022-08-30 20:37 UTC, jasperfurniss commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
> +    //   size: 'sm',
Same. Remove these.

2022-08-30 20:37 UTC, jasperfurniss commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
> +        {/* <If condition={dialog.cancelledButton || dialog.confirmedButton}>
Remove.

2022-08-31 16:27 UTC, Israel-Molestina commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
> +  // const [singleButtonOpen, toggleSingleButtonOpen] = useDialog()
Done!

2022-08-31 16:27 UTC, Israel-Molestina commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
> +    //   size: 'sm',
Done

2022-08-31 16:27 UTC, Israel-Molestina commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
> +        {/* <If condition={dialog.cancelledButton || dialog.confirmedButton}>
Done

2022-09-06 14:39 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_dialog/_dialog.jsx
> +  size?: "sm" | "md" | "lg" | 'status_size' | "content",
```suggestion
  size?: "sm" | "md" | "lg" | "status_size" | "content",
```

This and a few other places using single ticks vs doubles.

2022-09-06 14:39 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
> +      size: 'status_size',
```suggestion
      size: "status_size",
```

2022-09-06 14:39 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
> +      size: 'status_size',
```suggestion
      size: "status_size",
```

2022-09-06 14:39 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
> +      size: 'status_size',
```suggestion
      size: "status_size",
```

2022-09-06 14:39 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
> +      size: 'sm',
```suggestion
      size: "sm",
```

2022-09-07 14:24 UTC, thestephenmarshall requested changes
Still a lot of suggestions to commit here @Israel-Molestina

2022-09-07 14:24 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_dialog/_dialog.jsx
> +  size?: "sm" | "md" | "lg" | 'status_size' | "content",
```suggestion
  size?: "sm" | "md" | "lg" | "status_size" | "content",
```

2022-09-07 14:24 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
> +      size: 'sm',
```suggestion
      size: "sm",
```

2022-09-07 14:24 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
> +      size: 'sm',
```suggestion
      size: "sm",
```

2022-09-07 14:24 UTC, thestephenmarshall commented on playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
> +      size: 'sm',
```suggestion
      size: "sm",
```

2022-09-07 20:31 UTC, thestephenmarshall approved these changes

2022-09-07 20:56 UTC, merged