[PLAY-329]- Upgrade Font Awesome to 6.2.0
powerhome/playbook pull request #2085
Opened 2022-09-21 15:52 UTC by nidaqg

#### Screens

![Screen Shot 2022-09-21 at 11 41 09 AM](https://user-images.githubusercontent.com/73710701/191550631-6a5f1424-d6ee-4902-89d9-bd1fec5461ab.png)

#### Breaking Changes

No breaking changes, upgraded font awesome to 6.2.0, it is [backward compatible](https://fontawesome.com/v6/docs/web/setup/upgrade/whats-changed#backward-compatibility)

#### Runway Ticket URL

[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-329)

#### How to test this

- Test  kits that use icons to make sure icons are rendering correctly. Examples: Icon kit, Circle Icon kit, Selectable Icon Card kit, etc. 
- Test React as well as Rails version of these kits.

#### Checklist:

- [ ] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [ ] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [ ] **SCREENSHOT** Please add a screen shot or two.
- [ ] **SPECS** Please cover your changes with specs.
- [ ] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

2022-09-21 15:58 UTC, jasperfurniss approved these changes

2022-09-27 17:35 UTC, jasoncypret commented
Creating your alpha now

2022-09-28 14:14 UTC, thestephenmarshall requested changes
~~Blocking this one bc I'm still seeing `Font Awesome Pro 5.12.1` and the `regular-min.js` file size has gone from 1.3MB to 2.8MB! Something is wrong here..~~ Disregard.

2022-09-29 16:04 UTC, thestephenmarshall approved these changes

2023-01-14 22:53 UTC, closed without merging