[PLAY-443]  Body kit style <b>, <strong>, and <a>
powerhome/playbook pull request #2247
Opened 2023-01-11 16:59 UTC by Israel-Molestina

#### Screens

<img width="825" alt="Screen Shot 2023-01-11 at 11 52 07 AM" src="https://user-images.githubusercontent.com/73671109/211868660-b8d8203b-77e5-4a65-911c-961c87333c79.png">

#### Breaking Changes

NO

#### Runway Ticket URL

[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-443)

#### How to test this

To test, make sure b strong and a tags within a Body tag have correct styling

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

2023-01-17 13:15 UTC, jasperfurniss approved these changes

2023-01-17 16:17 UTC, jasoncypret requested changes

2023-01-17 16:17 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_body/_body.scss
> +    font-weight: 700;
2 things:

1. Always use our tokens if they are available. If they are not question why they are not and get them created.
2. Why not just include the styling for title 4? [Import this](https://github.com/powerhome/playbook/blob/master/playbook/app/pb_kits/playbook/tokens/_titles.scss) and add `@include pb_title_4;`

2023-01-17 16:17 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_body/_body.scss
> +  }
```suggestion
  a {
    color: $primary;
    &:hover {
      color: $text_lt_default;
    }
  }
```

2023-01-17 16:17 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_body/_body.scss
> +  }
This is easier to read

2023-01-17 16:17 UTC, jasoncypret commented on playbook/app/pb_kits/playbook/pb_body/docs/_body_styled.md
> +* `a` tag styles:  `color: $primary` and `color: $text_lt_default` on hover.
Can we just say it's styled like the title size 4? We don't do this breakdown of the styles in any other docs. I don't suggest doing it here. What if we change the letter spacing styles...then we have to remember to update the docs?

2023-01-23 17:50 UTC, jasperfurniss approved these changes

2023-01-23 18:08 UTC, jasoncypret approved these changes

2023-01-23 18:40 UTC, merged