[PLAY-493] dialog kit animation
powerhome/playbook pull request #2248
Opened 2023-01-12 15:45 UTC by Israel-Molestina

#### Screens

<img width="540" alt="Screen Shot 2023-01-12 at 10 44 12 AM" src="https://user-images.githubusercontent.com/73671109/212112891-6feae083-e918-4ea7-acff-366b598ea801.png">

#### Breaking Changes

NO

#### Runway Ticket URL

[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-493)

#### How to test this

Open a left or right full height dialog and ensure it comes in for the left or right and not the top

#### Checklist:

- [x] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** Please add the `Milano` label when you are ready for a review.
- [x] **SCREENSHOT** Please add a screen shot or two.
- [x] **SPECS** Please cover your changes with specs.
- [x] **READ DOCS** Please make sure you have read and understand the [Playbook Release Process](https://github.com/powerhome/playbook/wiki/Playbook-Releases)

2023-01-17 13:17 UTC, jasperfurniss approved these changes

2023-01-17 16:25 UTC, jasoncypret reviewed
I see the rails spec updated, why not the jest test?

2023-01-17 16:28 UTC, jasoncypret requested changes
I'm not sure where it's set but the exit animation needs tweaked. What is the speed? Can we slow the exit down...or separate the two animation speeds on the overlay and modal body?

2023-01-23 15:08 UTC, jasoncypret approved these changes

2023-01-23 18:40 UTC, merged