Use Docker Back
powerhome/playbook pull request #2602
Opened 2023-06-14 18:54 UTC by mfilipe

**What does this PR do?**

Change CI to make use of Docker Bake to improve the build speed with cache. 

Runway card: [GOG-790](https://nitro.powerhrg.com/runway/backlog_items/GOG-790)

2023-06-20 14:47 UTC, jasperfurniss submitted a review, later dismissed

2023-06-21 18:19 UTC, TeamTeaTime requested changes
@mfilipe Can you also update the `.dockerignore` here?

2023-06-21 18:54 UTC, TeamTeaTime reviewed
I think we can improve the Dockerfile here by splitting into two paths (kind of like the other ones). One path for playbook that runs `yarn install`, another for playbook-website that runs `bundle install`. In the prod stage it might also be possible to run the two `yarn release` commands in parallel and then combine their outputs. 

We can also add the yarn cache mount on the `yarn install` command, to help keep size down and just be prepared for when we have proper cache mounts.

2023-06-21 19:12 UTC, TeamTeaTime commented on Dockerfile
The way this is written currently leaves all the node_modules in the final image. It might be the case that they need to be there to support some existing workflow but otherwise we should keep them out by only copying the final output of the `yarn release`. This is a slightly unusual project so we should probably just check if the team expects them to be there for whatever reason.

2023-06-26 18:30 UTC, mfilipe commented on Dockerfile
>  RUN --mount=type=secret,id=yarnenv,required cd playbook-website; env $(cat /run/secrets/yarnenv | xargs) yarn release
@TeamTeaTime `playbook-website` needs the assets generated by `playbook` to works, so it's not possible to parallelize both process.

2023-06-26 18:31 UTC, mfilipe commented on Dockerfile
https://github.com/powerhome/playbook/pull/2602#discussion_r1242593161

2023-06-26 19:51 UTC, jasperfurniss commented on Dockerfile
> +    env $(cat /run/secrets/yarnenv | xargs) yarn install
@mfilipe Sent you a message in connect. Do you a screenshot of what is being included? I'd be interested to know so i can verify and get you an answer.

2023-06-26 21:16 UTC, mfilipe commented on Dockerfile
> +    env $(cat /run/secrets/yarnenv | xargs) yarn install
@jasperfurniss sent to you in Connect but I will post here as well: 

<img width="695" alt="Screenshot 2023-06-26 at 17 10 20" src="https://github.com/powerhome/playbook/assets/8762/a2a4c519-9ad1-4944-94f2-fa2dc4623014">

Those are `node_modules` created by `yarn install`.

2023-06-29 15:56 UTC, TeamTeaTime approved these changes

2023-07-06 14:44 UTC, ryanmrodriguez commented on Jenkinsfile
> +
👀 \s\s\s\s

2023-07-10 07:33 UTC, ryanmrodriguez approved these changes

2023-07-10 11:30 UTC, nidaqg commented
I see you approved this one @ryanmrodriguez , is it ready for merging and is there anything we need to look out for when we do merge it?

2023-07-10 13:15 UTC, mfilipe commented
> I see you approved this one @ryanmrodriguez , is it ready for merging and is there anything we need to look out for when we do merge it?

Regarding the code, I believe this PR is good now. What we need is someone to check if the final result of this PR (project deployed) is working as expected.

2023-07-10 14:11 UTC, jasperfurniss approved these changes

2023-07-10 14:50 UTC, merged