[PLAY-1145] Move Icon Page
powerhome/playbook pull request #3072
Opened 2024-01-23 20:29 UTC by markdoeswork

**What does this PR do?** A clear and concise description with your runway ticket url.

Runway: https://nitro.powerhrg.com/runway/backlog_items/PLAY-1145

**Screenshots:** Screenshots to visualize your addition/change
![screenshot-127 0 0 1_3000-2024 01 23-15_28_47](https://github.com/powerhome/playbook/assets/38965626/7b5fa459-fc74-4f35-ae7e-8326096e067d)

**How to test?** Steps to confirm the desired behavior:
1. Go to /beta/icons
2. witness icons

#### Checklist:
- [😈] **LABELS** Add a label: `enhancement`, `bug`, `improvement`, `new kit`, `deprecated`, or `breaking`. See [Changelog & Labels](https://github.com/powerhome/playbook/wiki/Changelog-&-Labels) for details.
- [x] **DEPLOY** I have added the `milano` label to show I'm ready for a review.
- [😈] **TESTS** I have added test coverage to my code.

2024-01-24 13:29 UTC, thestephenmarshall approved these changes
Code looks good to me. I tested `/beta/icons` in Milano and it is rendering correctly.

2024-01-24 15:15 UTC, jasperfurniss requested changes
@markdoeswork Go ahead and delete those extra files you had in here... looks like we added a views directory. But I think you realized we had one called "pages" already. 

Another piece of feedback from product is this: We can go ahead and remove the route that is on the legacy (current) site for `/icons`.... 
So we will _only_ work in the `beta/icons` for the time-being, until we are ready for launch. Thanks @markdoeswork

2024-01-24 15:15 UTC, jasperfurniss commented on playbook-website/app/javascript/components/Website/src/views/Icons.tsx
Let's remove this file @markdoeswork

2024-01-24 15:15 UTC, jasperfurniss commented on playbook-website/app/javascript/components/Website/src/views/README.md
Please delete this added file.

2024-01-26 19:13 UTC, jasperfurniss approved these changes

2024-01-26 21:38 UTC, merged